name: Build onyx Kernel

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout kernel
        uses: actions/checkout@v4
        with:
          repository: MiCode/Xiaomi_Kernel_OpenSource
          ref: onyx-v-oss
          fetch-depth: 1
          path: kernel

      - name: Hello
        run: |
          cd kernel
          ls -la arch/arm64/configs/ | grep onyx
          echo "Found onyx configs"
