name: Build onyx Kernel

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout kernel
        uses: actions/checkout@v4
        with:
          repository: MiCode/Xiaomi_Kernel_OpenSource
          ref: onyx-v-oss
          fetch-depth: 1
          path: kernel

      - name: Clone ReSukiSU
        run: |
          cd $GITHUB_WORKSPACE
          GH_PROXY="https://ghfast.top/"
          git clone --depth 1 -b "main" "${GH_PROXY}https://github.com/ReSukiSU/ReSukiSU.git" ReSukiSU || \
          git clone --depth 1 -b "main" "https://github.com/ReSukiSU/ReSukiSU.git" ReSukiSU
          ls -la ReSukiSU/

      - name: Hello
        run: echo "OK"
